version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo "Running tests..."
      - chmod +x test.sh
      - ./test.sh
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - index.html
